# This file can be used with Docker and Docker Compose to run this Couchbase example locally. This is solely meant to
# make testing and iterating faster and easier. See examples/local-mocks for instructions.

version: '3'
services:
  couchbase-0: &couchbase_config
    image: gruntwork/couchbase-${OS_NAME}-test
    entrypoint: ["/entrypoint/entrypoint.sh"]
    container_name: ${CONTAINER_BASE_NAME}-0

    # Required to make systemd happy
    privileged: true

    volumes:
      # Used for systemd
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

      # Mount these scripts so we get hot reload
      - ../../../modules/couchbase-commons:/opt/couchbase-commons
      - ../../../modules/run-couchbase-server/run-couchbase-server:/opt/couchbase/bin/run-couchbase-server
      - ../../../modules/run-sync-gateway/run-sync-gateway:/opt/couchbase-sync-gateway/bin/run-sync-gateway

      # Override scripts with mocks so we can run locally, without talking to AWS APIs
      - ../../local-mocks/aws.sh:/opt/gruntwork/bash-commons/aws.sh
      - ../../local-mocks/mount-volume.sh:/opt/couchbase-commons/mount-volume.sh

      # Mount the scripts we use to run Couchbase during Docker container boot
      - ../user-data:/user-data
      - ../../local-mocks/entrypoint.sh:/entrypoint/entrypoint.sh

    environment:
      # The User Data script that will be executed on boot by entrypoint.sh
      USER_DATA_SCRIPT: /user-data/user-data.sh

      # Any environment variable starting with USER_DATA_ENV_ will be read in by entrypoint.sh and made available in
      # the User Data script, with the USER_DATA_ENV_ portion stripped off.
      USER_DATA_ENV_cluster_asg_name: mock-couchbase-asg
      USER_DATA_ENV_cluster_port: 8091
      USER_DATA_ENV_cluster_size: 2
      USER_DATA_ENV_sync_gateway_interface: :4984
      USER_DATA_ENV_sync_gateway_admin_interface: 127.0.0.1:4985
      USER_DATA_ENV_mock_aws_region: us-east-1
      USER_DATA_ENV_mock_availability_zone: us-gov-west-1a
      USER_DATA_ENV_data_volume_device_name: /dev/xvdf
      USER_DATA_ENV_data_volume_mount_point: /couchbase-data
      USER_DATA_ENV_index_volume_device_name: /dev/xvdg
      USER_DATA_ENV_index_volume_mount_point: /couchbase-index
      USER_DATA_ENV_volume_owner: couchbase
      USER_DATA_ENV_data_node_container_base_name: ${CONTAINER_BASE_NAME}

    # Map each container to unique ports on the host. Note that you can talk to this container from your host OS via the
    # HTTP/REST APIs but NOT the Couchbase SDKs! The SDKs will try to connect to the internal node IPs, which can only
    # be accessed from within a container. Host networking would work around this, but it doesn't work, because
    # Couchbase doesn't allow all port numbers to be overridden, so the Erlang Port Mapper service clashes.
    # https://developer.couchbase.com/documentation/server/current/install/install-ports.html
    ports:
      - "${WEB_CONSOLE_PORT}:8091"
      - "${SYNC_GATEWAY_PORT}:4984"

  couchbase-1:
    <<: *couchbase_config
    container_name: ${CONTAINER_BASE_NAME}-1
    ports:
      # Map these ports to any available port number on the host
      - "8091"
      - "4984"
